server {
    listen 80;
    listen 20245;
    listen 443 ssl;
    server_name www.chodackiart.pl;

    ssl_certificate     /etc/letsencrypt/live/chodackiart.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chodackiart.pl/privkey.pem;

    return 301 $scheme://chodackiart.pl$request_uri;
}

server {
    listen 80;
    listen 20245;
    listen 443 ssl;
    server_name chodackiart.pl;

    ssl_certificate     /etc/letsencrypt/live/chodackiart.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chodackiart.pl/privkey.pem;

    index index.php index html;
    root /var/www/html/;
    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}